### ISSUE TITLE
Japan/Tokyo timezone (JST) setting

### ISSUE THREAD

**Issue by PuceBaboon** [fowlerk/ESP8266-Color-Weather-Station-v8#1]
Keith,

   Sorry, not an issue; I just haven't managed to work out how to submit a pull request yet.  Here's a diff on the latest, main WeMos...V8.ino file for the Tokyo/JST timezone.

690a687,692
>   } else if (TZ_CITY == "Tokyo") {
>         UTC_OFFSET = +9;
>         StartRule = (dstRule) {"JST", First, Sun, Nov, 1, 0}; 	  // Japan Standard time = UTC/GMT +9 hours.
>         EndRule = (dstRule) {"JST", First, Sun, Nov, 1, 0};       // NO DST.
>         #define NTP_SERVERS "3.jp.pool.ntp.org", "0.jp.pool.ntp.org", "2.jp.pool.ntp.org"
>         IS_METRIC = true;

   Excellent work on extending Dani's original, by the way.  I really like the update panels, even though my eyes are a bit too far gone nowadays to read the tiny text.  :-)

   Best wishes from Nagano-ken,

                -John-

**Comment by fowlerk** [comment]
Hi John...glad you liked my enhancements.  And yes, it's a bit tough for my eyes sometimes also (I have to use the reading glasses!), though I do like the compact size.  Maybe a port to a larger screen if I find a reasonably priced alternative in the future?

I've added your input on the time-zone settings for Tokyo.  Take care, and greetings from Kentucky.
