### ISSUE TITLE
simpleDSTadjust.h

### ISSUE THREAD

**Issue by andy1967** [fowlerk/ESP8266-Color-Weather-Station-v8#3]
keep getting error for  #include <simpleDSTadjust.h> and i cannot find a simpleDSTadjust.h that will work

**Comment by fowlerk** [comment]
This library was developed by Neptune and was included in Squix78's examples; here's the link to his repository for it:  https://github.com/neptune2/simpleDSTadjust.  Sorry for the trouble, I didn't include links to all of the other libraries that had been previously used, though it would probably make sense to document these in the future.  I'm working on some bug fixes and icon enhancements and will try to add those links when I complete the next round of changes.

**Comment by fowlerk** [comment]
This library was developed by Neptune and was included in Squix78's examples; here's the link to his repository for it:  https://github.com/neptune2/simpleDSTadjust. Sorry for the trouble, I didn't include links to all of the other libraries that had been previously used, though it would probably make sense to document these in the future. I'm working on some bug fixes and icon enhancements and will try to add those links when I complete the next round of changes.

**Comment by andy1967** [comment]
not a problem  and thanks for replying. now i'm having a new issue with the drawDateTime();

G:\MY Documents\Arduino\weather_station_V8\weather_station_V8.ino: In function 'void loop()':

weather_station_V8:440: error: 'drawDateTime' was not declared in this scope

     drawDateTime();

                  ^

G:\MY Documents\Arduino\weather_station_V8\weather_station_V8.ino: In function 'void updateData()':

weather_station_V8:544: error: 'drawDateTime' was not declared in this scope

   drawDateTime();

                ^

G:\MY Documents\Arduino\weather_station_V8\weather_station_V8.ino: In function 'void updateBotPanel()':

weather_station_V8:576: error: too few arguments to function 'void drawCurrentObservations(int16_t, int16_t)'

       drawCurrentObservations();

                               ^

G:\MY Documents\Arduino\weather_station_V8\weather_station_V8.ino:200:6: note: declared here

 void drawCurrentObservations(int16_t x, int16_t y);

      ^

exit status 1
'drawDateTime' was not declared in this scope

**Comment by fowlerk** [comment]
Very strange...I was able to recompile the code fine on my system.  After looking at your errors, I did notice that a function prototype was not declared for the drawDateTime function, so I added one.  Also, it appears that I had a typo on the prototype declare for drawCurrentObservations (there should be no arguments).  I corrected this also.  The code for with these changes has been uploaded to the repo to replace the original.  My experiences with the Arduino IDE are that it appears a little flaky or inconsistent in the order in which functions are compiled (or at least it seems to change from IDE version to version), so many times adding these declarations to the beginning of the code solve some of these types of errors.  BTW, I'm running v1.6.12 of the IDE...I'd be curious as to which one you're running to see if that explains why mine compiles and yours doesn't.

Try downloading the changed Weather_Station_v8.ino and see if that corrects your errors.  Also, BTW, v9 contains a lot of updates and bug-fixes; you may want to try that one.

**Comment by fowlerk** [comment]
You say you're adding it in a tab?  As in the Arduino IDE?  This (and the other includes discussed) are libraries.  If you don't know how to add libraries to the IDE, let me know and I'll try to summarize it quickly for you.

**Comment by andy1967** [comment]
the IDE that i have is 1.6.8 will get the 1.6.12 and see if that works

**Comment by andy1967** [comment]
Ok i figured out all the errors but i would like to know where i can find how to read the local and remote sensors  Thanks in advanced

**Comment by fowlerk** [comment]
Sounds like you're almost there!  Those are the defaults you'd expect to
see if none of the initial configuration settings have been made.  Look at
my detailed response to how to configure it via the configuration portal
and try again.

**Comment by andy1967** [comment]
ok thanks i will give a closure and see if i just missed it  , all else seems to me working ok. just have to mount it in a case
