### ISSUE TITLE
Not really an issuues

### ISSUE THREAD

**Issue by andy1967** [fowlerk/ESP8266-Color-Weather-Station-v8#6]
Not really an issue but where do i enter my WundergroundClient API Key and my ThingspeakClient and Last but not least  how do i get it to connect to my wifi?

**Comment by fowlerk** [comment]
I'd attempted to document the basics in the README, though admittedly it is a little brief as I was trying to avoid repeating the details already documented elsewhere under each library.  But, here's the basics for the initial configuration:

1. First, as noted in the README, I do not use an external DHT sensor nor Thingspeak.  I've kept the original code for these that was in Neptune's original example, but commented out the configuration and calls.  If you elect to use these, you'll need to go to the "Settings.h" tab, locate the settings for the Thingspeak channel, uncomment and change these for your implementation.  Also, you'll need to search the main routine for calls to Thinkspeak and uncomment as appropriate.  Note that I've not tested any of this myself.

2.  The initial configuration is done via a configuration portal or webpage.  The first time you bring up the app, if it cannot find previously stored settings, it will bring up an access point and configuration portal.  Look for an access point that begins with "ESP..." and connect to it.  It is a captive portal, and in most cases a browser will open automatically connecting to the portal after connection.  If it doesn't, then type the address "192.168.4.1" in a browser to bring it up once connected to the AP.  It should be fairly self-explanatory at that point; enter your WiFi AP/password credentials, WeatherUnderground API key, WU weather station, timezone city from the list, etc., and click "Save".  The ESP should restart and try to connect using the new configuration.  There's other features of the configuration portal, such as scanning for all available access points and allowing you to just select one, but again, it's pretty self-explanatory once you see the configuration page.

3.  If it doesn't connect, then you can at any time bring up the configuration portal again manually by double-clicking the reset button on the WeMos D1 mini.  (This doesn't have to be done really fast, just two resets within 10 seconds.)  You should also see information on the LCD display when it comes up in config mode.

4.  The initial defaults for the configuration portal are located on the "Settings.h" tab as well.  If you look through this, you'll find parameters for the WU API key, the timezone city, weather station, etc.  These are currently set for my location and preferences, but you can change them here if you want also.

That's pretty much it...
